version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "2020:8989"   # external port 2020 -> internal 8989
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    restart: always

volumes:
  mysql_data:
