name : CI - Spring boot
on:
    push:
        branches: ['main','master']
    pull_request:
        branches: ['main']    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # repository checkout
            - name: Checkout source code
              uses: actions/checkout@v4
           
            #   set up JDK
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: maven
            #  build with maven
            - name: Build with Maven Wrapper
              run: ./mvnw -B clean package
